### ISSUE TITLE
新教务系统选课若教室列表加载时间过长则不会出现“辅助”button

### ISSUE THREAD

**Issue by E011011101001** [zhouii/Tongji_Helper#10]
体育课教务系统 getTeachClass4Limit API 的 Response 为 389KB，由于网络问题响应时间较长，如图两次尝试分别用了 19.29s 和 9.82s。
![Screenshot from 2021-03-01 10-32-44](https://user-images.githubusercontent.com/50290471/109445174-f7165700-7a79-11eb-9596-7617646608c1.png)
此时“辅助”button 无法加载出来，如下图。
![Screenshot from 2021-03-01 10-42-35](https://user-images.githubusercontent.com/50290471/109445593-e1556180-7a7a-11eb-9b19-70cafa00cddf.png)

**Comment by zhouii** [comment]
啊没想到还有3秒以上的请求，我之前把超时设成3秒了，现在在https://github.com/zhouii/Tongji_Helper/commit/1f1605932d57dcfeac7294f5909d13ca2db66a0c 去掉超时了，不论多久都不会有问题了。已经提交2.1版本，在通过Google审核后所有用户都能自动更新
