### ISSUE TITLE
明文的验证码被替换，现在已无法自动登录

### ISSUE THREAD

**Issue by majiaxin110** [zhouii/Tongji_Helper#3]
<img width="1319" alt="Snipaste_2020-10-28_16-39-18" src="https://user-images.githubusercontent.com/28682970/97412269-4e75b080-193c-11eb-8366-e815a5cbe0ff.png">

目前统一身份认证替换掉了原来的明文验证码，目前是从服务端请求得到的一张图片了，所以已无法自动登录...不过验证码图片很简单，我想是不是能搞自动识别

**Comment by hwjnqq** [comment]
我觉得可，也不是很乱，调用一下百度的ocr?

**Comment by skyleaworlder** [comment]
:sob:

**Comment by zhouii** [comment]
验证码终于升级成真正的图片验证码了，Tongji Helper团队正在通过机器学习方法奋力解决此问题，很快就会升级出支持自动登录的版本。——蓝猫，于2020年10月29日
